### ISSUE TITLE
🚨 BREAKING CHANGES 0.6.0 -> 0.7.0

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1000]
This issue is created to keep track breaking changes between `0.6.0` and `0.7.0` (scheduled release on Oct. 26, 2020)

## Breaking Changes & Migration Guide

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1005 #1034  | Not yet | |

- `Document.id` in Protobuf is now a string type variable, this applies also to `Document.parent_id` and `Relevance.ref_id`
- `id` is filled with the hexdigest of [blake2b algorithm](https://docs.python.org/3.7/library/hashlib.html#hashlib.blake2b), which takes the document content into consideration.
- `SortQL.field` is now using `dunder_get` syntax rather than `.` expansion, e.g. `a.b.c -> a__b__c`, `score.value -> score__value`. It now supports `dict` and `list` access.
- `first_doc_id`, `random_doc_id` and `override_doc_id` are removed from CLI. 

---

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #983 #995 #1000 #1001 #1003 #1006 #1007  #1011 #1027 #1039 #1036  | Not yet |  |

- `granularity_range`, `adjacency_range`, `recur_on` and `recursion_order` are deprecated and don't work anymore
- Replaced by `traversal_paths`, which allows to decribe the part of the data structure, where the traversal should happen.
-- `['r']` for example only applies an Executor on the root node
-- `['c', 'r']` applies an Executor on the chunks of the root node and the root node itself
-- `['m', 'r']` applies an Executor on the matches of the root node and the root node itself
- Removed the `_apply` function and only kept `_apply_all` in `BaseRecursiveDriver`. Rationale: The Executor itself should do the iteration over the documents, as most Executors did anyhow. Currently, there is no need for the added complexity of a dedicated `_apply` function.

---

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1031 |  | |
- a new log config YAML schema is introduced, see appendix below
- `--log-config` is added to `jina pea` CLI, by default it points to `logging.default.yml`.
- `--log-sse`, `--log-profile`, `--log-with-own-name` are removed from `jina pea` CLI. They are now mapped to different resource files as below:

| filename | logger in the code |
|  --- | --- |
| logging.default.yml | `default_logger` and any logger defined with `JinaLogger()` |
| logging.docker.yml | `logger` used in the `ContainerPea`|
| logging.profile.yml |  `profile_logger`|
| logging.remote.yml | `logger` used in the `RemotePea`|

**Appendix: New Log Config YAML Schema**

```yaml
handlers:  # enabled handlers, order does not matter
  - StreamHandler
  - SysLogHandler
  - FluentHandler
level: INFO  # set verbose level
configs:
  FileHandler:
    format: '%(asctime)s:{name:>15}@%(process)2d[%(levelname).1s]:%(message)s'
    output: 'jina-{uptime}.log'
    formatter: JsonFormatter
  StreamHandler:
    format: '{name:>15}@%(process)2d[%(levelname).1s]:%(message)s'
    formatter: ColorFormatter
  SysLogHandler:
    ident: # this will be prepend to all messages
    format: '{name:>15}@%(process)2d[%(levelname).1s]:%(message)s'
    host: # when not given then record it locally, /dev/log on linux /var/run/syslog on mac
    port: # when not given then record it locally,  /dev/log on linux /var/run/syslog on mac
    formatter: PlainFormatter
  FluentHandler:
    # this configuration describes where is the fluentD daemon running and waiting for logs to be emitted.
    # FluentD then will have its own configuration to forward the messages according to its own syntax
    # prefix will help fluentD filter data. This will be prepended for FluentD to easily filter incoming messages
    tag: jina
    host: 0.0.0.0
    port: 24224
    format:
      host: '%(hostname)s'
      process: '%(process)s'
      type: '%(levelname)s'
```

---

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1049 | Not yet | |
- Protobuf `request_id` is now `string` type
- `--first-request-id` is removed from client CLI
- `--query-uses` and `--index-uses` from hello-world CLI is now renamed to `--uses-query` and `--uses-index`

---

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| |  | |
