### ISSUE TITLE
RouteDriver can't be used independently

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1067]
**Describe the bug**
The `RouteDriver` is bounded to `ControlReqRequest`. Currently, change the `executors._route.yml` to the following will break the flow. 

```
!BaseExecutor
with: {}
metas:
  name: route
requests:
  on:
    IndexRequest:
      - !RouteDriver {}
    ControlRequest:
      - !RouteDriver {}
    SearchRequest:
      - !RouteDriver {}
```

**Describe how you solve it**

---

**Environment**

**Screenshots**
