### ISSUE TITLE
Add possibility to provide dict-like parameter to executor from `yaml`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1091]
**Describe the feature**
Right now we cannot provide parameters in our Executors in the form of `dictionaries` when instantiated from yaml files (which is the main entrydoor to jina and to extending jina functionality in the `hub`).

It could be useful to add this so that configuration dictionaries can dinamically be passed through the Yaml interface without needing to change code.

A Yaml examle right now can look like this:
```
!Executor
with:
  param1: $param1
  param2: $param2
```

Maybe we could add the possibility to add:

```
!Executor
with:
  param1: $param1
  param2: $param2
  dictparam:
     - key1: $value1
     - key2: $value2
```
