### ISSUE TITLE
top_k is not working on multiple shards 

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/jina#1404]
**Describe the bug**
Problem is on query time. when i've multiple shards (>1) and if i set top_k == (total len of docs) on quey time than it's not returning all docs result. i also passing `polling='all'` and `uses_reducing='_merge_all'` on query flow still not working.

**Environment**
```
jina                          0.8.3
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.33.2
ruamel.yaml                   0.16.12
python                        3.7.9
platform                      Linux
platform-release              5.4.0-56-generic
platform-version              #62~18.04.1-Ubuntu SMP Tue Nov 24 10:07:50 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /media/kavan/WORK/Job/jina_search_engine/venv/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
```

**Comment by JoanFM** [comment]
Hey @Kavan72, could you give an example of the flow u are working with and the total length that you mean? Are you using any segmenter? Is the search done at root level or at chunk level?

**Comment by Kavan72** [comment]
my index flow:-
```
!Flow
pods:
  extractor:
    uses: pods/extract.yml
  encoder:
    uses: pods/encode.yml
    timeout_ready: 1200000
    read_only: true
  indexer:
    uses: pods/index.yml
    shards: 8
    separated_workspace: true
```

my query flow:-
```
!Flow
with:
  read_only: true
  port_expose: $JINA_PORT
pods:
  encoder:
    uses: pods/encode.yml
    timeout_ready: 60000
    read_only: true
  indexer:
    uses: pods/index.yml
    polling: all
    uses_reducing: _merge_all
    shards: 8
    separated_workspace: true
```
- with this flow i started index on 100 docs and after when i start query on this index that time i'm only getting only 50 to 60 result(even if i set top_k == 100, is working on shards=1 )
- i'm not using any segmenter.
- search done on root level.
