### ISSUE TITLE
Custom Drivers don't work in 0.8.4 and upwards

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1472]
Custom drivers work fine for me in 0.8.3. However, when I upgrade to 0.8.4 I get this error:
```
ruamel.yaml.constructor.ConstructorError: could not determine a constructor for the tag '!SentenceEncodeDriver'
```

My pod yml:
```
!SentenceEncoder
metas:
  py_modules:
    - sentence_encoder.py
    - sentence_encode_driver.py # driver file
requests:
  on:
    IndexRequest:
      - !SentenceEncodeDriver {} # cannot be found in sentence_encode_driver.py
    SearchRequest:
      - !EncodeDriver {}
```

sentence_encode_driver.py:
```
from jina.drivers.encode import EncodeDriver
from jina.types.sets.document_set import DocumentSet

class SentenceEncodeDriver(EncodeDriver):
  # implementation
```

**Comment by JoanFM** [comment]
Hey @janandreschweiger 

Would you be able to share the flow.yml (or an equivalent one) with the same structure and clarify which command and from where you are running it? So that we can reproduce in the best possible way?

Thanks!!

**Comment by janandreschweiger** [comment]
Sure here is my index-flow that fails:
```
!Flow
pods:
  crafter:
    uses: pods/craft-index.yml
  encoder:
    uses: pods/encode.yml  # fails here
    timeout_ready: 60000000
  chunk_idx:
    uses: pods/chunk.yml
  doc_idx:
    uses: pods/doc.yml
    needs: gateway
  join_all:
    uses: _merge
    needs: [doc_idx, chunk_idx]
```

I have another short question: I want to use the FaissIndexer (distance ... smaller is better) in combination with the TfIdfRanker (score ... larger is better). Do you have an idea how I could use both of them? My current implementation with the CollectMatches2DocRankDriver unfortunately gives the results in the wrong order.

Thank you @JoanFM for your time again!
