### ISSUE TITLE
Params not saved in config

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#1527]
There is a bug that when importing some encoders directly from the source file, all config params will not be saved. This is causing the failing tests in jina-ai/jina-hub#1349, although for some mysterious reason no failure occurs in jina-ai/jina-hub#1350.

To replicate, first cd to the proper folder (starting at the root of `jina-hub`):

```
cd encoders/nlp
```
Then, open a python terminal and execute
``` python
from TransformerTFEncoder import TransformerTFEncoder
encoder = TransformerTFEncoder('distilbert-base-uncased')
encoder.save_config()
```

Now examine the resulting file, it will look something like this
``` yaml
!TransformerTFEncoder
metas:
  name: TransformerTFEncoder.TransformerTFEncoder-1f530892
  pea_id: 0
  pea_workspace: .//None-{root.metas.pea_id}
  separated_workspace: false
requests:
  on:
    ControlRequest:
    - !ControlReqDriver
      with:
        priority: 0
    IndexRequest:
    - &id001 !EncodeDriver
      with:
        executor: null
        method: encode
        priority: 0
        traversal_paths:
        - c
        - r
    SearchRequest:
    - *id001
    TrainRequest:
    - *id001
```

Note that the custom parameters are not saved! I also get the same problem with `TransformerTorchEncoder`

If you replace the encoder import statement with 
``` python
from jina.hub.encoders.nlp.TransformerTFEncoder import TransformerTFEncoder
```

the whole thing will work, and the yaml file will have this at the end
``` yaml

with:
  layer_index: -1
  max_length: null
  model_save_path: null
  pooling_strategy: mean
  pretrained_model_name_or_path: distilbert-base-uncased
  truncation_strategy: longest_first
```
