### ISSUE TITLE
Jina Flow visualization with Inspect nodes

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1561]
**Describe the bug**
I have this Flow:

```
!Flow
version: '1.0'
pods:
  - name: encoder
    method: add
    uses: pods/encode.yml
    #parallel: $JINA_PARALLEL
    timeout_ready: 600000
    read_only: true
    needs: gateway
  - name: doc_indexer
    method: add
    uses: pods/doc.yml
    #shards: $JINA_SHARDS
    separated_workspace: true
    polling: all
    uses_reducing: _merge_all
    timeout_ready: 100000
    needs: encoder
  - name: evaluate_matching
    method: inspect
    uses: pods/evaluate_matching.yml
  - name: ranker
    method: add
    uses: ...
    uses_internal: pods/rank.yml
    #parallel: $JINA_PARALLEL
    timeout_ready: 600000
    needs: doc_indexer
  - name: evaluate_ranking
    method: inspect
    uses: pods/evaluate_ranking.yml

```

which leads to visualization:

![image (12)](https://user-images.githubusercontent.com/19825685/103304852-f32e7000-4a09-11eb-9499-c1c5e7113709.png)

when `include_last_pod: bool = False` is added to `flow/base.py` in the default parameters of `gather_inspect` method, the visualisation improves but still the gather_inspect pod is duplicated:

![image (13)](https://user-images.githubusercontent.com/19825685/103304906-19eca680-4a0a-11eb-8c44-38c0eafc1f7e.png)

There must be a way to change the `include_last_pod` parameter as a `Flow` argument or something and then the gather_inspect should only be added once.
