### ISSUE TITLE
🗑 [DEPRECATED] 0.9.0 -> 1.0.0

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1728]
# List of deprecated codes & Migration Guide

## Template
| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1730  | Yes  | `output_fn` and `callback` are deprecated and the argument name is from now on `on_done` |
| #1729  | Yes  | `MinRanker` and `MaxRanker` are deprecated, please use `SimpleAggregateRanker` with the specific parameters. |
|#1746 | Yes | `batch_size` is deprecated from `client` arguments. Now `request_size` must be used. Change inserted to better clarify the difference in concepts between `batch_size` at `Driver` and `Executor` level and the one at `client` side |

For #1729 
 If you were using `MinRanker` you will most likely want to use:

```yaml
!SimpleAggregateRanker
with:
  aggregate_function: 'min'
  is_reversed_score: true
```

If you were using `MaxRanker` you will most likely want to use:

```yaml
!SimpleAggregateRanker
with:
  aggregate_function: 'max'
  is_reversed_score: false
```

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> v0.9.0 </td>
<td> v1.0.0 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
old codes
```

</sub> </td>
<td> <sub> 

```python
new codes
```

</sub> </td>
</tr>
</table>

---
