### ISSUE TITLE
Permanently delete documents from storage

### ISSUE THREAD

**Issue by ace-kay-law-neo** [jina-ai/jina#1984]
Hey Jina team!

As described [here](https://docs.jina.ai/chapters/crud/index.html#limitations) documents persist the deletion and are only marked as inaccessible.

My question: Is there a possibility to delete documents from storage without reindexing everything again? Deletion performance isn't an issue for us, but reindexing everything is very inconvenient in our use case.

Thanks! I really appreciate your kind support.

**Sub-tasks**

- [x] Delete from NpIndexer. @ #2046 
- [x] Delete from BinaryPbIndexer. @ https://github.com/jina-ai/jina/pull/2102

**Comment by geraldwinkler** [comment]
@ace-kay-law-neo Same for me. I want to delete a big number of documents at once without reindexing. (usually as at night)

**Comment by FionnD** [comment]
Hey @ace-kay-law-neo and @geraldwinkler 

This is definitely a limitation we are aware of. When we added the delete feature in the last release, we decided that using the mark was better from a performance/speed/ram usage perspective. We are aware that we have to have a deeper conversation and maybe reassess our original choice. 

It is on our short-term roadmap [next release] to reassess and provide an update. In the meantime, if it's useful to you, please add an 👍 emoji to the original post we can see how important it is!

**Comment by nero-nazok** [comment]
Same for me here, performance isn't really important as deletion only happens at night and all at once.

**Comment by janandreschweiger** [comment]
@FionnD Same for me. Delete is kind of a bulk operation that happens once a day. Any updates?

**Comment by FionnD** [comment]
Unfortunately not yet @janandreschweiger. The next release will be at the end of March. Just to try and understand your usecases. 

Could you explain your situation in a little more depth, it might help us find a solution.

**Comment by janandreschweiger** [comment]
@FionnD Oh, that's a pity. We really need such a feature.

**Situation**
As many others here, reindexing really is a pain for us. In our case we would have to crawl, download and encode all documents from various sources again. Indexing, updating and also deletion happens once a day (usually at night). Therefore, it would be cool to have some kind of a bulk delete or just a possibility which removes all unaccessible documents (= marked as deleted) from the storage to prevent reindexing. Without such a feature, the storage will grow overtime until it reindexing is required. For us it is especially necessary to delete the documents from the storage, in order to comply with the GDPR (DSGVO).

Another thing is that our documents consist of text chunks, which should also be deleted. But I think this was already mentioned in this [issue](https://github.com/jina-ai/jina/issues/1986). Maybe you could also have a look on it.

Thanks for your effort, I hope you find a solution to our problem soon.

**Comment by cristianmtr** [comment]
Hey @ace-kay-law-neo 

We are currently looking into this. Will get back to you once we release it.

**Comment by ace-kay-law-neo** [comment]
Thank you @cristianmtr. This feature is really important to us.

**Comment by cristianmtr** [comment]
Hey @ace-kay-law-neo 

As you can see from the status update, this is now possible for both NumpyIndexer and BinaryPbIndexer. 

You can check their usage in the two PRs I linked to in your comment.

Basically the parameter is `delete_on_dump`, which is set to `False` by default, but you should set to `True`. Let me know if there are any issues

They will be part of the new release.

**Comment by janandreschweiger** [comment]
Thanks @cristianmtr, you did us a huge favor ❤️!

I will try it out, as soon as I know how to delete the document along with its chunks. This issue was mentioned before [here](https://github.com/jina-ai/jina/issues/1986), but there haven't been any updates for two weeks. If Jina doesn't provide a solution out of the box, maybe the following approach would work:
1. store the chunk-ids of a document in one of its attributes (e.g. tags)
2. on-delete:
  1. BinaryPbIndexer: retrieve the document, write the chunk-ids to the request and delete the document
  2. NumpyIndexer: delete the chunks

Do you think this approach could work? Or will there be a ChildIdIndexer like @maximilianwerk mentioned in the issue any time soon?

Thanks again for your awesome support! 👍

**Comment by FionnD** [comment]
Hey @janandreschweiger , 

Unfortunately, we don't have the capacity to look issue https://github.com/jina-ai/jina/issues/1986 until next month. 

@cristianmtr might be able to offer advice on that proposal in the meantime tho..

**Comment by cristianmtr** [comment]
Basically what you need to hook into is here: https://github.com/jina-ai/jina/blob/a151006980b3a6f0065b3e197062f6654c77a74e/jina/drivers/segment.py#L37

You need to ouput/store the `c.id` (this is the `ids` of the newly created chunks from a Segmenter). You could store them in a file on disk and then save that somewhere. You could even add them as list to the tags of the parent doc. Then you can grab all of those and delete them.

You need to store the mapping between the parent Document's id and its chunks' ids. 

We will be looking at this soon, as @FionnD mentioned

**Comment by janandreschweiger** [comment]
Thank you @cristianmtr and @FionnD! 🙂

**Comment by janandreschweiger** [comment]
Hey @cristianmtr, I tried the delete_on_dump parameter yesterday. Although the documents are deleted and cannot be accessed via the search, the file-size doesn't decrease. In fact the file-size slightly increases by 1kB.

The documents are stored via one NumpyIndexer and one BinaryPbIndexer. I have tried setting the parameter directly in the yml configuration, but it still doesn't work.

```
!BinaryPbIndexer
  with:
    index_filename: chunk.gz
    delete_on_dump: true
  metas:
    name: chunk_idx
    workspace: $PATH_WORKSPACE
...
!NumpyIndexer
  with:
    index_filename: vec.gz
    delete_on_dump: true
  metas:
    workspace: $PATH_WORKSPACE
    name: wrap_idx
```

I would really appreciate it if you could help me out. Thanks!

**Comment by cristianmtr** [comment]
Hey @janandreschweiger What were the exact operations you performed? What is your data?

**Comment by janandreschweiger** [comment]
Thanks for your response @cristianmtr.
Thats strange, I use the latest version of Jina (1.0.8). In addition, the parameter is recognized by Jina, as I have to set it to False at index-time (otherwise I get an error).

Here is my full pod-config:
```
!CompoundIndexer
components:
  - !FaissIndexer
    with:
      index_key: Flat
      distance: l2
      requires_training: false
      index_filename: vec.gz
      ref_indexer:
        !NumpyIndexer
        with:
          index_filename: vec.gz
          delete_on_dump: true
        metas:
          workspace: $PATH_WORKSPACE
          name: wrap_idx
    metas:
      workspace: $PATH_WORKSPACE
      # name: wrap_idx
      name: faiss_idx
      is_trained: true  # may be removed
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
      workspace: $PATH_WORKSPACE
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: faiss_idx
          traversal_paths: ['c']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['c']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['c']
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: faiss_idx
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
    DeleteRequest:
      - !DeleteDriver
        with:
          executor: faiss_idx
      - !DeleteDriver
        with:
          executor: chunk_idx
```

As I already mentioned the documents cannot be accessed after I perform the deletion:
```
ids = [ ... ]
with AsyncFlow.load_config('./flow.yml') as f:
    async for entry in f.delete(ids):  # I also tried to set the parameter here
        print(entry)
```

Nevertheless, I will try it again and update my comment with my findings.

**Comment by cristianmtr** [comment]
`delete_on_dump` is only supported by NpIndexer and BinaryPbIndexer. Running it on the advanced indexer (like Faiss) will not work.

Can you try with a simple NpIndexer?

**Comment by janandreschweiger** [comment]
@cristianmtr I tried it with the plain NumpyIndexer, but unfortunately the size of the workspace doesn't decrease (but slightly increase):

```
!CompoundIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vec.gz
      delete_on_dump: true
    metas:
      workspace: $PATH_WORKSPACE
      name: wrap_idx
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
      workspace: $PATH_WORKSPACE
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: wrap_idx
          traversal_paths: ['c']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['c']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['c']
    DeleteRequest:
      - !DeleteDriver
        with:
          executor: wrap_idx
      - !DeleteDriver
        with:
          executor: chunk_idx
```

**Comment by ace-kay-law-neo** [comment]
Hi @cristianmtr and @janandreschweiger.
I tried out @janandreschweiger's example and I encountered the same issue. Any ideas what we do wrong @cristianmtr?

**Comment by cristianmtr** [comment]
You are deleting on a different level than you are indexing. This means that when you are deleting (and thus adding some new entries after the masking of delete -- see https://github.com/jina-ai/jina/blob/640daf4d389768be216dac4125ef4e837ee65d23/jina/executors/indexers/keyvalue.py#L214), you are actually not deleting anything but just adding. 

Possible solution: make sure you are keeping track of the ids of the chunks you are actually indexing and issue a request with those.

I will try to delve deeper into this in the next hours or tomorrow, but not sure when exactly. But that is my initial hunch

**Comment by janandreschweiger** [comment]
I already regarded that @cristianmtr. That's exactly what I do.
I store the chunk-ids at index time and use them for deletion. That's why there is no traversal_paths argument for the DeleteRequest. In addition, the deletion really works, as the chunks cannot be found afterwards, even though the documents themselves are not deleted. (The documents are stored on a mongo-database and don't get deleted yet.)
Nevertheless, the file-size is still the same for my workspace.

Thanks for looking into this @cristianmtr!

**Comment by cristianmtr** [comment]
Can you send me a full script of what you are doing?

**Comment by janandreschweiger** [comment]
Sure, should I create a repository and upload my code?

**Comment by cristianmtr** [comment]
> Sure, should I create a repository and upload my code?

Yes, please

**Comment by janandreschweiger** [comment]
No problem @cristianmtr. But that will take some time, as I will only keep the necessary parts. (< 1h) I will try to provide you with a minimal working example.

**Comment by cristianmtr** [comment]
What I'm interested in is:

- how do you create the Flow
- how do you create the Documents
- how do you create the chunks of the Documents
- what ids are you using to delete

**Comment by janandreschweiger** [comment]
Ok than it will just upload that.

**Comment by janandreschweiger** [comment]
Hey @cristianmtr sorry for waiting a little longer. I have sent you a git invitation to my repository. If you are missing something or have some questions regarding my code just write me a comment.

As you can see [here](https://github.com/janandreschweiger/jina_delete/blob/master/pods/doc/index/conversation/executor.py) the chunk-ids are saved to the database. And used again for deletion. I already checked them, they are the correct chunk-ids. So there should be no problem.

**Comment by cristianmtr** [comment]
Hey @janandreschweiger 

Tried to replicate and understand this more

I think if u are using too few docs it cannot go below a certain size:

```yml
!CompoundIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vector
      delete_on_dump: true
    metas:
      name: vector_idx
  - !BinaryPbIndexer
    with:
      index_filename: kv
      delete_on_dump: true
    metas:
      name: kv_indexer
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: vector_idx
      - !ExcludeQL
        with:
          fields: embedding
      - !KVIndexDriver
        with:
          executor: kv_indexer
    DeleteRequest:
      - !DeleteDriver
        with:
          executor: vector_idx
      - !DeleteDriver
        with:
          executor: kv_indexer

```

```python
import os
import shutil

from jina import Flow
from tests import get_documents

chunks = 0
same_content = False

os.environ['PATH_WORKSPACE'] = 'tmp_ws'
if os.path.exists('tmp_ws'):
    shutil.rmtree('tmp_ws')

docs = list(get_documents(chunks, same_content, nr=200, index_start=0, same_tag_content=None))

f = Flow().add(uses='idx.yml')
with f:
    f.index(docs)

print(os.system('du -sh tmp_ws/chunk_compound_idx/*'))

with f:
    f.delete([d.id for d in docs[:50]])


with f:
    f.delete([d.id for d in docs[:5]])

print(os.system('du -sh tmp_ws/chunk_compound_idx/*'))
```


```
BEFORE


12K	tmp_ws/chunk_compound_idx/kv
36K	tmp_ws/chunk_compound_idx/kv.head
4,0K	tmp_ws/chunk_compound_idx/kv_indexer.bin
12K	tmp_ws/chunk_compound_idx/vector
32K	tmp_ws/chunk_compound_idx/vector_idx.bin
0


AFTER

8,0K	tmp_ws/chunk_compound_idx/kv
28K	tmp_ws/chunk_compound_idx/kv.head
4,0K	tmp_ws/chunk_compound_idx/kv_indexer.bin
12K	tmp_ws/chunk_compound_idx/vector
24K	tmp_ws/chunk_compound_idx/vector_idx.bin
0
```
