### ISSUE TITLE
🚨 BREAKING CHANGES 1.1 -> 1.2

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2281]
# 🚨 BREAKING CHANGES 1.1 -> 1.2

This issue is created to keep track of breaking changes between `1.1` and `1.2` (scheduled release on 2021.04.26)

### Current version is [![PyPI](https://img.shields.io/pypi/v/jina?color=%23099cec&label=PyPI%20package&logo=pypi&logoColor=white)](https://pypi.org/project/jina/)

| PR |  Rolled Out? | Override |
| --- | --- | --- |
|  #2269 | Yes | |

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.1 </td>
<td> 1.2 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
from jina.executors.decorators import batching_multi_input
from jina.executors import BaseCrafter

class MyAwesomeCrafter(BaseCrafter):
    @batching_multi_input(batch_size=3, slice_nargs=2)
    def craft(self, blob, embedding, *args, **kwargs):
         pass
```

</sub> </td>
<td> <sub> 

```python
from jina.executors.decorators import batching
from jina.executors import BaseCrafter

class MyAwesomeCrafter(BaseCrafter):
    @batching(batch_size=3, slice_nargs=2)
    def craft(self, blob, embedding, *args, **kwargs):
         pass
```

</sub> </td>
</tr>
</table>

---

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #2243  | Yes | |

Index file name now always depends on the shard id too. Shard id always start at `0`.

Given an indexer with the following yaml:

```yaml
!UniqueVectorIndexer
components:
  - !DocCache
    metas:
      name: cache
  - !NumpyIndexer
    with:
      index_filename: vec.gz
      metric: euclidean
    metas:
      name: vec_idx
metas:
  name: inc_vecindexer
  workspace: $JINA_TEST_INCREMENTAL_INDEX_WORKSPACE
```

you now load it as follows:

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.1 </td>
<td> 1.2 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
BaseExecutor.load(random_workspace / 'inc_vecindexer' / 'vec_idx.bin')
```

</sub> </td>
<td> <sub> 

```python
BaseExecutor.load(random_workspace / 'inc_vecindexer' / 'vec_idx-0' / 'vec_idx.bin')
```

</sub> </td>
</tr>
</table>

---

| PR |  Rolled Out? | Override |
| #2313 | Yes | #2317 |
| #2317 | Yes | #2327 |
| #2327 | Yes | #2351 |
| #2351 | Yes | --- |

check out more details at #2313

---

## Template
| PR |  Rolled Out? | Override |
| --- | --- | --- |
| |  | |

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.1 </td>
<td> 1.2 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
old codes
```

</sub> </td>
<td> <sub> 

```python
new codes
```

</sub> </td>
</tr>
</table>

---
