### ISSUE TITLE
BaseUpdateDriver

### ISSUE THREAD

**Issue by ace-kay-law-neo** [jina-ai/jina#2283]
Hey everyone, I'd like to write a custom UpdateDriver. Unfortunately, there is not a single driver like for all the other request types (index, search, delete).

I would appreciate it, if you could add one. The KVIndexDriver would work absolutely fine in my opinion. One just needs to change the default method to 'update'. Thank you!!

**Comment by JoanFM** [comment]
Hey @ace-kay-law-neo ,

Why do u need to create a new Indexer.

You can use any `KVIndexDriver` and change the `method` to `update`.

```
requests:
  on:
    UpdateRequest:
      - !VectorIndexDriver
        with:
          method: update
          traversal_paths: [ 'r' ]

```
