### ISSUE TITLE
feat: support embedded exec `yaml_path` in flow yaml

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#246]
```yaml
!Flow
with:
  runtime: process
#  logserver: true
#  logserver_config: test-server-config.yml
pods:
  chunk_seg:
    yaml_path: craft/index-craft.yml
    replicas: $REPLICAS
    read_only: true
  doc_idx:  # embed YAML
    yaml_path:
      !DocPbIndexer
      with:
        index_filename: doc.gzip
      metas:
        name: doc_indexer  # a customized name
        workspace: $TEST_WORKDIR
  tf_encode:
    yaml_path: encode/encode.yml
    needs: chunk_seg
    replicas: $REPLICAS
    read_only: true
  chunk_idx:
    yaml_path: index/chunk.yml
  join_all:
    yaml_path: _merge
    needs: [doc_idx, chunk_idx]
    read_only: true
```
