### ISSUE TITLE
Error when searching with FaissIndexer.

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#2507]
Hi Jina team,
first of, congratulations for your new release. Your new features are amazing. We will implement one after another into our production version.

We discovered a bug/problem in the FaissIndexer. We experience this issue in Jina v1.1.10 and v1.3.0. When searching we get the following error:
```
dev_ai            | INFO:     10.0.0.17:59212 - "OPTIONS /search/?query=microsoft HTTP/1.1" 200 OK
dev_ai            |     AsyncClient@ 1[S]:connected to the gateway at 0.0.0.0:41477!
search |█                   | 📃      0 ⏱️ 0.0s 🐎 0.0/s      0   requestssearch ...             gateway@201[I]:prefetching 50 requests...
dev_ai            |         gateway@201[W]:if this takes too long, you may want to take smaller "--prefetch" or ask client to reduce "--request-size"
dev_ai            |         gateway@201[I]:prefetching 50 requests takes 0 seconds (0.00s)
dev_ai            |         encoder@189[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸⚐
dev_ai            | DEBUG | Message: <class 'list'>
dev_ai            | DEBUG | Message: Encoding 1 paragraphs
dev_ai            | INFO:faiss.loader:Loading faiss with AVX2 support.
dev_ai            | INFO:faiss.loader:Loading faiss.
dev_ai            | INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: /var/huforce/model
dev_ai            | INFO:sentence_transformers.SentenceTransformer:Load SentenceTransformer from folder: /var/huforce/model
Batches: 100%|██████████| 1/1 [00:00<00:00, 15.68it/s]        encoder@189[I]:#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 463 Bytes
dev_ai            |       chunk_idx@192[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸⚐
dev_ai            |    FaissIndexer@192[S]:memmap is enabled for /var/huforce/fs/workspace/wrap_idx-0/vec.gz
dev_ai            |       chunk_idx@192[I]:#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 3.6 KB
dev_ai            |       chunk_idx@192[E]:TypeError("unsupported operand type(s) for *: 'int' and 'NoneType'")
dev_ai            |  add "--quiet-error" to suppress the exception details
dev_ai            | Traceback (most recent call last):
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 201, in _msg_callback
dev_ai            |     self._zmqlet.send_message(self._callback(msg))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 187, in _callback
dev_ai            |     self._pre_h # may be removedook(msg)._handle(msg)._post_hook(msg)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 180, in _handle
dev_ai            |     self._executor(self.request_type)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 587, in __call__
dev_ai            |     d()
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/__init__.py", line 390, in __call__
dev_ai            |     self._apply_all(documents, *args, **kwargs)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/search.py", line 172, in _apply_all
dev_ai            |     idx, dist = self.exec_fn(embed_vecs, top_k=int(self.top_k))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/hub/indexers/vector/FaissIndexer/__init__.py", line 133, in query
dev_ai            |     dist, ids = self.query_handler.search(vecs, top_k)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/helper.py", line 975, in __get__
dev_ai            |     value = obj.__dict__[f'CACHED_{self.func.__name__}'] = self.func(obj)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/__init__.py", line 138, in query_handler
dev_ai            |     r = self.get_query_handler()
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/vector.py", line 279, in get_query_handler
dev_ai            |     vecs = self._raw_ndarray
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/helper.py", line 975, in __get__
dev_ai            |     value = obj.__dict__[f'CACHED_{self.func.__name__}'] = self.func(obj)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/vector.py", line 320, in _raw_ndarray
dev_ai            |     return np.memmap(
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/numpy/core/memmap.py", line 248, in __new__
dev_ai            |     size *= k
dev_ai            | TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
dev_ai            |          ranker@195[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸ranker/ZEDRuntime▸⚐
dev_ai            |          ranker@195[I]:#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 5.9 KB
dev_ai            |         doc_idx@198[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸ranker/ZEDRuntime▸doc_idx/ZEDRuntime▸⚐
dev_ai            |         doc_idx@198[I]:#sent: 0 #recv: 1 sent_size: 0 Bytes recv_size: 5.9 KB
search |█                   | 📃    100 ⏱️ 2.9s 🐎 34.7/s      1   requestsINFO:     10.0.0.17:59212 - "POST /search/?query=microsoft HTTP/1.1" 200 OK
dev_ai            | search takes 2 seconds (2.88s)
```

Our chunk-pod.yml:
```
!CompoundIndexer
components:
  - !FaissIndexer
    with:
      index_key: Flat
      distance: l2
      requires_training: false
      index_filename: vec.gz
      ref_indexer:
        !NumpyIndexer
        with:
          index_filename: vec.gz
          delete_on_dump: true
        metas:
          workspace: $PATH_WORKSPACE
          name: wrap_idx
    metas:
      workspace: $PATH_WORKSPACE
      name: faiss_idx
      is_trained: true
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
      workspace: $PATH_WORKSPACE
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
  py_modules: delete_driver.py
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: faiss_idx
          traversal_paths: ['c']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['c']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['c']
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: faiss_idx
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
    DeleteRequest:
      - !DeleteChunkDriver
        with:
          executor: faiss_idx
      - !DeleteChunkDriver
        with:
          executor: chunk_idx
```

When replacing the FaissIndexer in the above yml-configuration with the NumpyIndexer everything works fine.
We appreciate any help. Thank you!

**Comment by JoanFM** [comment]
Hey @janandreschweiger, does it seem that `top_k` is not properly handled? and is recognized as None?

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

could you provide more details about the `Flow` configuration to see if we can reproduce, are u using a docker image or the faiss executor directly?

**Comment by janandreschweiger** [comment]
Hey @JoanFM, thanks for your response!!

I think we handle the top_k argument correctly:
```
async for response in flow.search_lines(lines=['This is the query'], line_format='text', top_k=10):
   return response.search.docs[0].matches
```

We use the FaissIndexer directly as you can see from our chunk-pod.yml that I posted above.

Our search-flow config:
```
!AsyncFlow
with:
  logserver: false
  read_only: true
  show-exc-info: true
  return_results: true
pods:
  encoder:
    uses: pods/encode/pod.yml
    timeout_ready: 600000
  chunk_idx:
    uses: pods/chunk/pod.yml
  ranker:
    uses: pods/rank-pod.yml
  doc_idx:
    uses: pods/doc/search/pod.yml
```

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

Thank you for opening the issue. I manage to reproduce the issue and I found the problem.

The problem is the usage of `ref_indexer` in a `Flow` that is supposed to work both for `indexing` and `querying`, which is disencouraged. And to make it work for `1.3.0` it would imply a big change (which given the fact that 2.0 is on the line, the `ref_indexer` pattern will be removed and there will be a clear separation of concerns between querying and indexing).


For now, the way to make it work is:

Have 2 flows, in the `index` one have the `NumpyIndexer` that will be used as `ref_indexer` for the query-flow:

`indexer.yml` (to be put in the index flow)

```yaml
!CompoundIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vec.gz
      delete_on_dump: true
    metas:
      name: wrap_idx
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
  py_modules: delete_driver.py
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: wrap_idx
          traversal_paths: ['c']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['c']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['c']
    DeleteRequest:
      - !DeleteChunkDriver
        with:
          executor: wrap_idx
      - !DeleteChunkDriver
        with:
          executor: chunk_idx
```

and a query-indexer to be put in the query flow

```yaml
!CompoundIndexer
components:
  - !FaissIndexer
    with:
      index_key: Flat
      distance: l2
      requires_training: true
      index_filename: vec.gz
      ref_indexer:
        !NumpyIndexer
        with:
          index_filename: vec.gz
          delete_on_dump: true
        metas:
          name: wrap_idx
    metas:
      name: faiss_idx
      is_trained: true
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
metas:
  name: chunk_compound_idx
  workspace: $PATH_WORKSPACE
  py_modules: delete_driver.py
requests:
  on:
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: faiss_idx
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
```

Another point of pain I found is that u need to make sure that `encoder` encodes the data into `np.float32` at least for query time. (otherwise u can do that change in the `faiss` to make sure the conversion happens before calling `self.query_handler.search()`.

I hope this helps.

**Comment by JoanFM** [comment]
This is how I validated the proposed solution:

Created app.py

```python
import numpy as np
from jina.flow import Flow
from jina.types.document import Document
from jina.types.arrays.document import DocumentArray


def docs():
    return DocumentArray([Document(embedding=np.array([1., 1., 1., 1.], dtype=np.float32)) for _ in range(10)])


flow = Flow.load_config('index-flow.yml')

with flow:
    flow.index(inputs=docs(), request_size=2)

flow = Flow.load_config('query-flow.yml')

with flow:
    flow.search(inputs=docs(), request_size=2, top_k=1)
```

where `index-flow.yml` is:

```yaml
!Flow
with:
  logserver: false
  read_only: true
  show-exc-info: true
  return_results: true
pods:
  idx:
    uses: indexer.yml
```

and `indexer.yml` is:

```yaml
!CompoundIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vec.gz
      delete_on_dump: true
    metas:
      name: wrap_idx
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
metas:
  name: chunk_compound_idx
  workspace: './workspace'
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: wrap_idx
          traversal_paths: ['r']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['r']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['r']
```

and `query-flow.yml` is:

```yaml
!Flow
with:
  logserver: false
  read_only: true
  show-exc-info: true
  return_results: true
pods:
  idx:
    uses: query_indexer.yml
```

and `query_indexer.yml` is:

```yaml
!CompoundIndexer
components:
  - !FaissIndexer
    with:
      index_key: Flat
      distance: l2
      requires_training: true
      index_filename: vec.gz
      ref_indexer:
        !NumpyIndexer
        with:
          index_filename: vec.gz
          delete_on_dump: true
        metas:
          name: wrap_idx
    metas:
      name: faiss_idx
      is_trained: true
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
metas:
  name: chunk_compound_idx
  workspace: './workspace'
requests:
  on:
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: faiss_idx
          traversal_paths: ['r']
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
```
