### ISSUE TITLE
jina board does not work with gateway

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#281]
The following YAML file breaks down the [dashboard](https://jina-ai.github.io/dashboard/#/flow) because the `gateway` is considered as unknown pods. Adding a `gateway` pod at the beginning will solve the problem for the time being.

```yaml
!Flow
pods:
  splittor:
    yaml_path: yaml/craft-split.yml
  encoder:
    yaml_path: yaml/encode.yml
    timeout_ready: 60000
  chunk_indexer:
    yaml_path: yaml/index-chunk.yml
  doc_indexer:
    yaml_path: yaml/index-doc.yml
    needs: gateway
  join_all:
    yaml_path: _merge
    needs: [doc_indexer, chunk_indexer]
```
