### ISSUE TITLE
every BaseExecutor should has its default on_request YAML config

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#37]
for example, all encoders inherited from `BaseEncoder` should have the following as default

```yaml
requests:
  on:
    [SearchRequest, TrainRequest, IndexRequest]:
      - !EncodeDriver
        with:
            method: encode
```
