### ISSUE TITLE
Cannot use a hub executor in a yaml defined flow

### ISSUE THREAD

**Issue by matthewfranglen** [jina-ai/jina#3848]
**Describe the bug**

The yaml flow definition that is available does not seem to support jinahub executors.
I've tried to define it with:

```yaml
jtype: Flow
version: "1"
executors:
  - name: index
    uses:
      jtype: "jinahub://FaissIndexer"
      metas:
        workspace: $HW_WORKDIR
```

and when I load this I get the error:

```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!jinahub://FaissIndexer'
  in "<unicode string>", line 1, column 1:
    !jinahub://FaissIndexer
    ^
```

The yaml flow definitions seem to be very under documented. I found them through forking the examples. Are they still supported?

**Environment**
- jina 2.2.2
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.3
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.41.1
- pyyaml 6.0
- python 3.9.6
- platform Linux
- platform-release 5.4.0-89-generic
- platform-version #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021
- architecture x86_64
- processor x86_64
- uid 158278743441692
- session-id dd49ca2f-3b65-11ec-9b07-8ff42447411c
- uptime 2021-11-01T22:48:43.041939
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Comment by JoanFM** [comment]
Hello @matthewfranglen ,

Thanks for reporting the issue.

The correct flow definition in this case would be the following:

```yaml
jtype: Flow
version: "1"
executors:
  - name: index
    uses: "jinahub://FaissIndexer"
      metas:
        workspace: $HW_WORKDIR
```

As per the under documentation, we will try to act on it. Thanks very much, where did u find the missleading information?
