### ISSUE TITLE
X as a service: no matched driver for IndexRequest request

### ISSUE THREAD

**Issue by vforvoid** [jina-ai/jina#397]
After update to Jina 0.1.8 I can't run X as a service example any more.
I'm getting 

```encode@8395[E]:no matched driver for IndexRequest request, this pea is either badly configured or it is not configured to handle IndexRequest request```

I'm using the following yaml file for `encode` pod:

```
!TransformerTorchEncoder
with:
  pooling_strategy: cls
  model_path: /home/v/work/nlp/models/rubert-base-cased-conversational
  max_length: 96
```
