### ISSUE TITLE
Running the model locally

### ISSUE THREAD

**Issue by jyotikhetan** [jina-ai/jina#4073]
**I want to run the model locally**
 how can run any model locally, without pulling anything from hub..!! I tried cross modal replaced jinahub model by python script.. still it's connecting to hub to load.. process the thing..!! 

My Flow look like tihs now 
````
jtype: Flow                                      
version: '1'                                    
with:                                             
  prefetch: 10                                    
  port_expose: $JINA_PORT                         
  workspace: $JINA_WORKSPACE                      
pods:                                             
  - name: image_loader                            
    uses: ImageReader                            
    py_modules: 'flows/executors.py'              
    read_only: true                             
    needs: gateway                                
  - name: image_encoder                           
    uses : CLIPImageEncoder
    py_modules: 'flows/clip_image_encoder.py'                           
    needs: image_loader                           
  - name: image_indexer                           
    uses : SimpleIndexer
    py_modules: 'flows/simple_indexer.py'
         
    uses_with:                                    
      index_file_name: 'image_index'             
    needs: image_encoder                          
  - name: text_filter                            
    uses: TextFilter                             
    py_modules: 'flows/executors.py'             
    needs: gateway                              
  - name: text_encoder                          
    uses : CLIPTextEncoder
    py_modules: 'flows/clip_text_encoder.py'                        
    needs: text_filter                           
  - name: text_indexer                          
    uses: SimpleIndexer
    py_modules: 'flows/simple_indexer.py'
    uses_with:                                 
      index_file_name: 'text_index'              
    needs: text_encoder                           
  - name: join_all                             
    needs: [image_indexer, text_indexer]
```


**Please help me to understand, How I can proceed further on this**
