### ISSUE TITLE
think about setting volumes and default workspace for docker compose file

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4392]

**Comment by mapleeit** [comment]
# Context

I observed that if we add `volumes` and generate the docker compose file. The docker compose file won't add `mount volumes`. This could be a missing feature/bug. 

# Reproduce

## 1. Run snippet

```
from jina import Flow

f = Flow().add(uses='jinahub+docker://SimpleIndexer', volumes='/tmp/test:/tmp/test')

f.to_docker_compose_yaml()
```

## Open `docker-compose.yml` and check 

```yml
version: '3.3'
networks:
  jina-network:
    driver: bridge
services:
  executor0-head:
    image: jinaai/jina:3.0.2-py38-perf
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - executor0/head
    - --polling
    - ANY
    - --port-in
    - '8081'
    - --runtime-cls
    - HeadRuntime
    - --pod-role
    - HEAD
    - --connection-list
    - '{"0": ["executor0:8081"]}'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  executor0:
    image: jinahub/zb38xlt4:6215110fdbd7cde99b1bc0aa
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - executor0
    - --uses
    - config.yml
    - --port-in
    - '8081'
    - --uses-metas
    - '{}'
    - --native
    networks:
    - jina-network
  gateway:
    image: jinaai/jina:3.0.2-py38-standard
    entrypoint:
    - jina
    command:
    - gateway
    - --polling
    - ANY
    - --port-in
    - '51161'
    - --expose-endpoints
    - '{}'
    - --port-expose
    - '55659'
    - --graph-description
    - '{"executor0": ["end-gateway"], "start-gateway": ["executor0"]}'
    - --deployments-addresses
    - '{"executor0": ["executor0-head:8081"]}'
    - --pod-role
    - GATEWAY
    expose:
    - '55659'
    - '51161'
    ports:
    - 55659:55659
    - 51161:51161
    networks:
    - jina-network
```
