### ISSUE TITLE
CompoundExecutor needs `request` to be explicitly defined 

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#460]
**Describe the feature**

The field in `requests` *must* be explicitly defined, though it's quite straightforward. This hurts the usability of the compound YAML

```yaml
!CompoundExecutor
components:
  - !MySegmenter
    metas:
      name: myseg  # a customized name
  - !NumpyBuffer2PNGDataURI
    metas:
      name: buf2png
metas:
  name: compound_crafter
requests:
  on:
    [IndexRequest, SearchRequest]:
      - !SegmentDriver
        with:
          executor: myseg
      - !DocCraftDriver
        with:
          executor: buf2png
    ControlRequest:
      - !ControlReqDriver {}
```

**Your proposal**

Add default requests for `CompoundExecutor`

---

**Environment**

**Screenshots**
