### ISSUE TITLE
ConnectionError: failed to connect to all addresses on Mac M1

### ISSUE THREAD

**Issue by ugm2** [jina-ai/jina#4828]
**Describe the bug**

In my Macbook M1 Pro, I'm getting the following error when calling the Flow through an API:

```
ConnectionError: failed to connect to all addresses |Gateway: Communication error with deployment CustomTransformerTorchEncoder at address(es) {'0.0.0.0:50016'}. Head or worker(s) may be down.
```
---

**Environment**

I installed `jina==3.4.7` on my Macbook M1 Pro, along with:
```shell
elasticsearch==8.2.0
spacy==3.3.0
torch==1.13.0
transformers==4.19.2
```

And then starting my FastAPI with Jina using the following command:

```
sudo JINA_MP_START_METHOD=spawn python -m uvicorn neural_search.api.server:app --reload --host 0.0.0.0 --port 5001
```

Where I use `sudo` because otherwise the program can't access the folders in my Mac.

The flow yaml file used is the following:

```yaml
jtype: Flow
version: '1'

executors:
  - name: CustomTransformerTorchEncoder
    uses: 'CustomTransformerTorchEncoder'
    volumes: '~/.cache/huggingface:/root/.cache/huggingface'
    py_modules: 'neural_search/core/executors/encoder.py'
    uses_with:
      pretrained_model_name_or_path: 'sentence-transformers/all-MiniLM-L6-v2'
  - name: CustomIndexer
    uses: 'CustomIndexer'
    py_modules: 'neural_search/core/executors/indexer.py'
    install_requirements: True
    uses_with:
      traversal_right: '@c'
      traversal_left: '@r'
      n_dim: 512
    workspace: workspace
  - name: ranker
    uses: 'jinahub://SimpleRanker'
    install_requirements: True
    uses_with:
      metric: 'cosine'
      ranking: 'max'
      traversal_paths: '@c'
    volumes: 'workspace'
```

Where CustomTransformerTorchEncoder is in the following [link](https://github.com/ugm2/annual-report-intelligent-search/blob/main/neural_search/core/executors/encoder.py) and the CustomIndexer is in this other [link](https://github.com/ugm2/annual-report-intelligent-search/blob/main/neural_search/core/executors/indexer.py)

**Screenshots**

![image](https://user-images.githubusercontent.com/25923343/170208658-7866588b-5464-4a78-9857-5155046bb067.png)

In the screenshot, when starting the service, you can see there are some warnings hidden there, but they are not really shown.

After calling the Flow I get this:

![image](https://user-images.githubusercontent.com/25923343/170208969-05c0bf94-6c89-47d1-8ad2-f3671d83126b.png)
