### ISSUE TITLE
Document the Gateway to Gateway communication

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4943]
Right now the Gateway to Gateway communication is not document it should be.

Ex : using this jcloud flow :
```
jtype: Flow
jcloud:
    expose_gateway: true
executors:
  - name: indexer
    uses: jinahub+docker://SimpleIndexer
```

and connecting to use from an other flow:

```python
from jina import Flow
from docarray import DocumentArray, Document

f = Flow().add(
    tls=True, host='0cfd78a517.wolf.jina.ai', external=True, port=443
)

f.build()
print('hw')
with f:
    f.post('/', inputs=DocumentArray.empty(size=10))
    print('here')
```
