### ISSUE TITLE
kubernetes deployment: can not load the executor from config.yml 

### ISSUE THREAD

**Issue by hsalehgh** [jina-ai/jina#4987]
First Thank you so much for your great platform and on time responses. I am trying to deploy a simple flow in kubernetes. I have dockerzied my exceutor and indexer based on jina document and run dockers and both where working fine. Here is my docker file for indexer:
**config.yaml:**
```yaml
jtype: SimpleIndexer
uses_with:
  match_args: {}
uses_metas:
  name: SimpleIndexer
  description: "SimpleIndexer does indexing and searching"
  py_modules:
    - simple_indexer.py
  workspace: './workspace'
uses_request:
  /index: index
  /search: search
```
**simple_indexer.py**

```python
import inspect
import os
from typing import Dict, Optional

from jina import DocumentArray, Executor, requests
from jina.logging.logger import JinaLogger


class SimpleIndexer(Executor):


    FILE_NAME = 'index.db'

    def __init__(
        self,
        match_args: Optional[Dict] = None,
        table_name: str = 'simple_indexer_table',
        traversal_right: str = '@r',
        traversal_left: str = '@r',
        **kwargs,
    ):
  
        super().__init__(**kwargs)

        self._match_args = match_args or {}
        self._index = DocumentArray(
            storage='sqlite',
            config={
                'connection': SimpleIndexer.FILE_NAME,
                'table_name': table_name,
            },
        )  # with customize config
        self.logger = JinaLogger(self.metas.name)
        self.default_traversal_right = traversal_right
        self.default_traversal_left = traversal_left

    @property
    def table_name(self) -> str:
        return self._index._table_name

    @requests(on='/index')
    def index(
        self,
        docs: 'DocumentArray',
        **kwargs,
    ):
        """All Documents to the DocumentArray
        :param docs: the docs to add
        """
        if docs:
            self._index.extend(docs)

    @requests(on='/search')
    def search(
        self,
        docs: 'DocumentArray',
        parameters: Optional[Dict] = None,
        **kwargs,
    ):
        """Perform a vector similarity search and retrieve the full Document match

        :param docs: the Documents to search with
        :param parameters: the runtime arguments to `DocumentArray`'s match
        function. They overwrite the original match_args arguments.
        """
        match_args = (
            {**self._match_args, **parameters}
            if parameters is not None
            else self._match_args
        )

        traversal_right = parameters.get(
            'traversal_right', self.default_traversal_right
        )
        traversal_left = parameters.get('traversal_left', self.default_traversal_left)
        match_args = SimpleIndexer._filter_match_params(docs, match_args)
        docs[traversal_left].match(self._index[traversal_right], **match_args)

    @staticmethod
    def _filter_match_params(docs, match_args):
        # get only those arguments that exist in .match
        args = set(inspect.getfullargspec(docs.match).args)
        args.discard('self')
        match_args = {k: v for k, v in match_args.items() if k in args}
        return match_args

    @requests(on='/delete')
    def delete(self, parameters: Dict, **kwargs):
        """Delete entries from the index by id

        :param parameters: parameters to the request
        """
        deleted_ids = parameters.get('ids', [])
        if len(deleted_ids) == 0:
            return
        del self._index[deleted_ids]

    @requests(on='/update')
    def update(self, docs: DocumentArray, **kwargs):
        """Update doc with the same id, if not present, append into storage

        :param docs: the documents to update
        """

        for doc in docs:
            try:
                self._index[doc.id] = doc
            except IndexError:
                self.logger.warning(
                    f'cannot update doc {doc.id} as it does not exist in storage'
                )

    @requests(on='/fill_embedding')
    def fill_embedding(self, docs: DocumentArray, **kwargs):
        """retrieve embedding of Documents by id

        :param docs: DocumentArray to search with
        """
        for doc in docs:
            doc.embedding = self._index[doc.id].embedding

    @requests(on='/clear')
    def clear(self, **kwargs):
        """clear the database"""
        self._index.clear()
```
And at the end this is my flow:

```python
f = Flow(port=8080).add(name='torch_encoder', uses='docker://ACOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-encoder:0.1').add(name='torch_indexer', uses='docker://ACOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-indexer:0.1')
f.to_kubernetes_yaml('./k8s_flow', k8s_namespace='test-flow')

```
When I do `kubectl apply -R -f ./k8s_flow`  the status of the indexer pod is **CrashLoopBackOff** and when I look at the logs of the pod I see the following error:
`CRITI… torch_indexer@ 1 can not load the executor from config.yml`

Also when I run flow locally it perfectly works. Any help is really appreciated!

**Comment by JoanFM** [comment]
can u share the details on how u have created the 2 docker images so that we can try to reproduce with the most similar setting possible?

**Comment by hsalehgh** [comment]
Here is how I created docker file:
```
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    git \
    python3.7 \
    python3-pip \
    vim

RUN pip install jina

#Setup Workdir
RUN mkdir /executor_root

COPY . /executor_root/

WORKDIR /executor_root

RUN pip install -r gpu_requirements.txt

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
```

**Comment by hsalehgh** [comment]
This is also k8s yaml file generated by `f.to_kubernetes_yaml` in case you need
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torch-indexer
  namespace: test-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torch-indexer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: torch-indexer
        jina_deployment_name: torch_indexer
        ns: test-flow
        pod_type: WORKER
        shard_id: '0'
    spec:
      containers:
      - args:
        - executor
        - --name
        - torch_indexer
        - --k8s-namespace
        - test-flow
        - --uses
        - config.yml
        - --port
        - '8080'
        - --port-monitoring
        - '9090'
        - --uses-metas
        - '{}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: torch_indexer
        envFrom:
        - configMapRef:
            name: torch-indexer-configmap
        image: ACCOUNTNUMBER.dkr.ecr.us-west-2.amazonaws.com/hs-torch-indexer:0.1
        imagePullPolicy: IfNotPresent
        name: executor
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
```

**Comment by hsalehgh** [comment]
I double checked and I named my config file config.yml for both executors.

**Comment by JoanFM** [comment]
can you share the `gpu_requirements.txt`? Also it would be interesting to set `JINA_LOG_LEVEL=DEBUG` inside the Deployments and then share the logs of the failing Pods to see if we can get more information.

 ```yaml
        - name: JINA_DEPLOYMENT_NAME
          value: torch_indexer
        - name: JINA_LOG_LEVEL
          value: DEBUG
```
