### ISSUE TITLE
Generated k8s YAML should respect the `replicas` specified in Flow YAML 

### ISSUE THREAD

**Issue by zac-li** [jina-ai/jina#5043]
Per https://docs.jina.ai/fundamentals/flow/yaml-spec/#gateway-arguments, looks like as if the k8s YAML generated via `flow.to_k8s_yaml` should use the `replicas` specified in Flow YAML, but it's not the case.

It'll be great if the generated k8s YAML respect the `replicas` specified in Flow YAML. 

For example, Flow YAML:
```
jtype: Flow
with:
  protocol: grpc
  replicas: 2
....
```
should result in the generated k8s YAML include 
```
spec:
  replicas: 2
```
