### ISSUE TITLE
How to avoid CUDA OOM

### ISSUE THREAD

**Issue by nhtlongcs** [jina-ai/jina#5095]
Hi, thanks for great ml-infrastructure framework.
I met a memory problem; how can I limit the number of requests per replica to avoid CUDA out of memory?

---

**Environment**
```
- jina 3.7.14
- docarray 0.15.4
- jcloud 0.0.35
- jina-hubble-sdk 0.15.2
- jina-proto 0.1.13
- protobuf 3.19.4
- proto-backend cpp
- grpcio 1.47.0
- pyyaml 6.0
- python 3.8.5
- platform Linux
- platform-release 5.4.0-124-generic
- platform-version #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022
- architecture x86_64
- processor x86_64
- uid 258520883455093
- session-id fe56aa6b-2634-11ed-ba65-eb1f956ce475
- uptime 2022-08-27T18:20:56.208439
- ci-vendor (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
```

**Comment by samsja** [comment]
Glad that you like our framework :smile: 

One solution to `limit the number of requests` to avoid OOM is to use the `prefetch` argument. 
```python
from jina import Flow
with Flow(prefetch=100).add(...):
         ...
```
This will limit the Flow to only accept X requests at the same time. Please refer to the documentation : https://docs.jina.ai/fundamentals/gateway/#limit-outstanding-requests

I hope that it answers your question

**Comment by nhtlongcs** [comment]
Hi @samsja, thanks for your response. This is my full `flow.yml` content. But currently, I can still request more than two times without any exception, and OOM cases occur whenever I do that. You can also take a look on my full source code [here](https://github.com/nhtlongcs/live-novel) adopted from DiscoArt. Is there anything I misunderstand about the param `prefetch`?  

```
jtype: Flow
with:
  protocol: grpc
  monitoring: true
  cors: true
  port: 51001
  port_monitoring: 51002  # prometheus monitoring port
  prefetch: 1
  env:
    JINA_LOG_LEVEL: debug
executors:
  - name: StableAI
    uses: StableAIExecutor
    py_modules:
      - executors.py
    env:
      CUDA_VISIBLE_DEVICES: RR0:2 
    replicas: 1  
    floating: true
  - name: poller
    uses: ResultPoller
    py_modules:
      - executors.py
```
