### ISSUE TITLE
Better Kubernetes readiness probes

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#5198]
If we export `f.yml` to Kubernetes yamls, here's how the `readinessProbe` looks now for Gateway & Executor.

```yaml
# f.yml
jtype: Flow
with:
  port: 12345
executors:
  - name: e1
```

#### Current
```yaml
      readinessProbe: 
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket: 
            port: 8080
```
#### Proposal
```yaml
      readinessProbe:
          exec:
            command:
              - jina 
              - ping 
              - executor 
              - 127.0.0.1:8080
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
```

#### Current
```yaml
      readinessProbe: 
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket: 
            port: 12345
```

#### Proposal
```yaml
    readinessProbe:
          exec:
            command:
              - jina 
              - ping 
              - flow 
              - grpc://127.0.0.1:12345
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
```

The probes are tested in JCloud Kubernetes cluster for the above Flow.
