### ISSUE TITLE
Proposal feature: Add Secrets object concept to Jina

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5238]
**Problem**
Right now we have a problem with Jina that users need to pass in code or YAML sensitive information as tokens, passwords etc in `Jina YAMLs` or `Jina Python scripts`.

This exposes our users security.

**Proposal**
As an MLOps framework, we can create our own Secret concept  analoguous to the Kubernetes Secret concept. The main difference is that in the Jina core we will not store or manage these secrets, only expose the logic on how these secrets have to be passed and read from the `Executors (microservices)`.

I suggest to create `secret` objects in Jina that can be attached to Flow (Gateway) or Executors both in YAML and in Python. Something similar to this (THESE DETAILS COULD CHANGE):

```yaml
jtype: Flow
secrets:
  - name: secret_gateway
    type: env
    key: JINA_SECRET_GATEWAY
executors:
  - name: preprocessor
    secrets:
      - name: secret_executor
        type: env
        key: JINA_SECRET1
    uses_with:
      confidential: ${{ SECRET.JINA_SECRET_EXECUTOR }}
```

```python
from jina import secrets

f = Flow(secrets=[{'name': 'secret_gateway', 'type': 'env','key': 'JINA_SECRET_GATEWAY'}]).add(secrets=[{'name': 'secret_executor', 'type': 'env','key': 'JINA_SECRET1'}], uses=PreProcessor, uses_with={'admin_emails': 'secrets.secret_executor'})
```

**User journey**
I believe the user journey can make sense accross all the ways Jina can be used. The same way `Kubernetes` separates the concerns of `creating` SECRETS and reading or accessing them in Pods we can do the same in Jina.

- Reading and accessing SECRETS in code is handled by these objects and the YAML python representation/interface

- Creating the SECRETS would remain in the user responsability in the following ways:
     - When running Flows locally, simply set environment variables or store information in file system
     - When running with Kubernetes, make sure to create K8s screts, `f.to_kubernetes_yaml` will do best effort to map `secrets` object to K8s secrets objects
     - JCloud would eventually offer a `secrets` API to manage these objects before a Flow is created in JCloud

**Example**

With this feature, this PR #5221 could work like this:

```YAML

jtype: Flow
secrets:
  - name: secret_external_deployment
    type: env
    key: JINA_SECRET_CAS
executors:
  - name: clip-as-service
    external: True
    grpc_metadata: 
         - authentication_token: ${{SECRETS.JINA_SECRET_CAS}}
```
This would allow the user to store this `Flow.yml` without storing confidential or security problematic information

**Extra helpers**
Maybe we can provide extra helpers in Executors to read automatically from secrets in the future

**Implementation**

- [ ] Create Secrets objects and define their key-value structure
- [ ] Make them a Deployment argument in parser and make sure they are handled by JAMLCompatible
- [ ] Make sure in the local Flow YAML, the envs are properly passed to the new processed and that the ${{SECRETS.XXX}} or any agreed syntax is properly implemented to access the `secrets` INSIDE the `Executor` or `Gateway` code
- [ ] Handle in `to_kubernetes_yaml` with best effort the transformation to the `readFromEnv` and `readFromValue` for `Deployments`
- [ ] JCloud offer an API to expose that easily in the K8s cluster
