### ISSUE TITLE
Invoke Flow like a pipeline

### ISSUE THREAD

**Issue by big-thousand** [jina-ai/jina#5487]
**Describe your proposal/problem**

I want to invoke jina api like a image pipeline.
Because the executor may cost too many time, I add a kafka producer at the end of flow to notify handle success
So I don't need the http response
**I wish that http response can return immediately when the flow have recevice the http request**
How can I do this

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
Helllo @big-thousand ,

So what u want is to have the Gateway return kind of an acknowledgement while running in the backward the Executor pipeline and u can urself retrieve the success by an Executor which does so?

**Comment by big-thousand** [comment]
yes, I will retrieve the success from kafka because the executor may cost too much time

**Comment by JoanFM** [comment]
Like now you have this option:

1. Use Floating Executors which declares an Executor as floating (and therefore a subset of Flow) to be floating, which means that Gateway does not wait for it to respond.
https://docs.jina.ai/fundamentals/flow/add-executors/#floating-executors

2. In next release we are going to release a feature that will allow the user to define their own CustomGateway similar to how you can define an Executor. Then u could be able to define a CustomGateway that creates a task that sends the Docs to Executors but does not await it. SO we would give the user full control of the gateway. You can see a preview of the Documentation (not yet ready here). https://docs-custom-gateway--jina-docs.netlify.app/fundamentals/gateway/custom-gateway/#gateway-runtime-arguments

**Comment by big-thousand** [comment]
Can I use Floating Executors in k8s

**Comment by big-thousand** [comment]
Thanks for help!
I will try it

**Comment by JoanFM** [comment]
If you find any problem, please do not hesitate to let us know

**Comment by big-thousand** [comment]
@JoanFM 
when I try flow executor with floating
The last executor will receive request with len(docs) == 0
My Flow is like this
I export it to k8s for deploy
```
jtype: Flow
version: '1'
with:
  protocol: http
  port: 9080
  monitoring: true
  port_monitoring: 50080
  tracing: false
  metrics: false
executors:
  - name: img_preprocess_operator
    uses: jinahub+docker://QImagePreprocessOperator/latest
    monitoring: true
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    port: 9080
    jcloud:
      resources:
        memory: 4G
        cpu: 2
    floating: true
  - name: img_operator
    uses: jinahub+docker://QImageOperator/latest
    monitoring: true
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    port: 9080
    uses_with:
    jcloud:
      resources:
        memory: 4G
        cpu: 2
        # gpu: 1
    floating: true
  - name: storage_operator
    uses: jinahub+docker://QStorageOperator/latest
    monitoring: true
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    port: 9080
    jcloud:
      resources:
        memory: 4G
        cpu: 2
    uses_with:
      'kafka_bootstrap_servers': 'redpanda-cluster-0.redpanda-cluster.redpanda-cluster-default.svc.cluster.local:9093'
      'kafka_auth': False
    needs: 'img_operator'
    floating: true
```

**Comment by big-thousand** [comment]
The first flow is slow because it will crop border and check watermark and upload to s3.

**Comment by JoanFM** [comment]
I would like to create a Flow like this:

```python
from jina import Flow, Executor, requests

class CheckExecutor(Executor):

    @requests
    def foo(self, docs, **kwargs):
        print(len(docs))

f = Flow().add(name='Exec1', uses='jinahub+docker://QImagePreprocessOperator/latest', floating=True).add(name='Exec2', uses='jinahub+docker://QImageOperator/latest', floating=True, needs=['Exec1']).add(uses=CheckExecutor, floating=True, needs=['Exec2'])

with f:
    f.post(on='/', inputs=??)

```

**Comment by big-thousand** [comment]
```
inputs = DocumentArray(
    [
        Document(uri="https://cdn.pixabay.com/photo/2021/09/28/13/14/cat-6664412_1280.jpg", id="12313"),
    ]
)
```

**Comment by JoanFM** [comment]
Do u have any dummy implementation of the first Executors? in terms of input and output of the docs?

**Comment by big-thousand** [comment]
the full flow is like this, but it need s3 and kafka
```
jtype: Flow
version: '1'
with:
  protocol: http
  port: 9080
executors:
  - name: img_preprocess_operator
    uses: jinahub+docker://QImagePreprocessOperator/latest
    port: 9080
    uses_with:
      's3_endpoint': "xxxxxxx"
      's3_access_key': "xxxxxxxx"
      's3_secret_key': "xxxxxxxxx"
      's3_budget': "xxxxx"
    jcloud:
      resources:
        memory: 4G
        cpu: 2
    floating: true
  - name: img_operator
    uses: jinahub+docker://QImageOperator/latest
    port: 9080
    uses_with:
    jcloud:
      resources:
        memory: 4G
        cpu: 2
        # gpu: 1
    floating: true
  - name: storage_operator
    uses: jinahub+docker://QStorageOperator/latest
    port: 9080
    jcloud:
      resources:
        memory: 4G
        cpu: 2
    uses_with:
      'kafka_bootstrap_servers': 'xxxxxxxx'
      'kafka_auth': False
    needs: 'img_operator'
    floating: true
```

**Comment by JoanFM** [comment]
It is weird, I do not see any problem here. 

If I do this:

Flow YAML (It mimics your Topology, but with letting pass executors)
```yaml
jtype: Flow
version: '1'
with:
  protocol: http
  #port: 9080
  monitoring: false
  port_monitoring: 50080
  tracing: false
  metrics: false
executors:
  - name: img_preprocess_operator
    #uses: jinahub+docker://QImagePreprocessOperator/latest
    monitoring: false
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    jcloud:
      resources:
        memory: 4G
        cpu: 2
  - name: img_operator
    #uses: jinahub+docker://QImageOperator/latest
    monitoring: false
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    uses_with:
    jcloud:
      resources:
        memory: 4G
        cpu: 2
        # gpu: 1
    floating: true
  - name: storage_operator
    #uses: jinahub+docker://QStorageOperator/latest
    uses: CheckExecutor
    monitoring: false
    port_monitoring: 50080
    tracing: false
    metrics: false
    traces_exporter_host: grpc://otlp.uptrace.dev
    traces_exporter_port: 4317
    metrics_exporter_host: grpc://otlp.uptrace.dev
    metrics_exporter_port: 4317
    jcloud:
      resources:
        memory: 4G
        cpu: 2
    uses_with:
      'kafka_bootstrap_servers': 'redpanda-cluster-0.redpanda-cluster.redpanda-cluster-default.svc.cluster.local:9093'
      'kafka_auth': False
    needs: 'img_operator'
    floating: true
```

and then I do:

```python
from jina import Flow, Executor, requests, DocumentArray, Document


class CheckExecutor(Executor):

    @requests
    def foo(self, docs, **kwargs):
        print(len(docs))


f = Flow.load_config('flow.yml')

with f:
    f.post(on='/', inputs=DocumentArray(
        [
            Document(uri="https://cdn.pixabay.com/photo/2021/09/28/13/14/cat-6664412_1280.jpg", id="12313"),
        ]
    ))

```

I see that it prints `1` as the length received.
