### ISSUE TITLE
Create Deployment YAML separate from Executor YAML

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5552]
create deployment yaml separate from Executor yaml

* add Deployment.load_config

A deployment can use an Executor YAML like so:
 Deployment(uses='executor.yaml', replicas=...)

But a deployment YAML is used like so:
Deployment.load_config(uses='deployment.yaml')

Possible usages of executors inside Flow YAML:
1. executor config is embedded in config
```yaml
 jtype: flow
 executors:
   - jtype: Deployment
     uses:
         jtype: MyExecutor
         py_modules: executor.py
     replicas: 2
```

2. old usage for backward compatibility:
```yaml
 jtype: flow
 executors:
    - uses: executor.yaml
      replicas: 12
```
3. ~~simply `deployment.yaml`~~
```yaml
 jtype: flow
 executors:
    - uses: deployment.yaml
      replicas: 2
      shard: 3
```
instead check if this is possible:
```yaml
 jtype: flow
 executors/deployments:
   - deployment.yaml
   - uses: executor.yaml
      replicas: 12
   - jtype: Deployment
     uses:
         jtype: MyExecutor
         py_modules: executor.py
     replicas: 2
```

Deployment args include protocol, shard, replicas, expose-gateway

Executor args include the rest
