### ISSUE TITLE
Change documentation for `CONTEXT` environment variables

### ISSUE THREAD

**Issue by npitsillos** [jina-ai/jina#5585]
**Describe your proposal/problem**

The [docs](https://docs.jina.ai/concepts/flow/yaml-spec/#context-variables) don't specify how to use context variables in a flow yaml.

It should be made clear that when defining a flow using the YAML specification `VALUE_A` & `VALUE_B` should appear in the `env` key.

---
**Flow.yml**
```
jtype: Flow
executors:
  - name: executor1
    uses: executor1/config.yml
    env:
      VALUE_A: 123
      VALUE_B: hello
    uses_with:
      var_a: ${{ CONTEXT.VALUE_A }}
      var_b: ${{ CONTEXT.VALUE_B }}
```
