### ISSUE TITLE
Gateway closing during execution of PDF indexing flow

### ISSUE THREAD

**Issue by themantalope** [jina-ai/jina#5596]
**Describe the bug**
The gateway closes during execution of the flow. There is not a single file that triggers the cause. I have ~16K single page PDF files, I am indexing them.

I'm not sure what exactly is happening. I do not get memory errors or other errors/output from gRPC to suggest that the message size or anything is too big.

Typically the flow will close around the 30th to 50th file. Sometimes as early as the 9th file.

Will attach log files, and code examples

`index-pdf-flow-cpu.yml`:
```yaml
jtype: Flow
version: '1'
with:
  protocol: 'grpc'
  cors: True
  port_expose: $JINA_PORT
  env:
    JINA_LOG_LEVEL: DEBUG
  monitoring: True
executors:
  - name: pdfocr
    uses: OCRMyPDF
    install_requirements: True
    uses_with:
      command_line_options: '--force-ocr'
    uses_requests:
      '/index': extract_text
  - name: pdfsegmenter
    uses: jinaai+docker://jina-ai/PDFSegmenter:latest
    install_requirements: True
  - name: sentenizer
    uses: jinaai://jina-ai/Sentencizer:latest
    install_requirements: True
  - name: encoder
    uses: jinahub+docker://AudioCLIPTextEncoder/latest
    uses_with:
      traversal_paths: '@cc'
      model_path: /tmp/.cache/AudioCLIP-Full-Training.pt
      tokenizer_path: /tmp/.cache/bpe_simple_vocab_16e6.txt.gz
    volumes: $MODEL_MOUNT_ASSETS
    install_requirements: True
  - name: pdftextindexer
    uses: jinaai://jina-ai/SimpleIndexer:latest
    uses_metas:
      workspace: $JINA_WORKSPACE/text_indexer
      traversal_right: '@cc'
      traversal_left: '@cc'
    install_requirements: True
    volumes: $WORKSPACE_MOUNT
    needs: encoder
```

`ocrmypdf_executor.py`:
```python
from jina import Executor, DocumentArray, requests
import ocrmypdf
from subprocess import Popen, PIPE


class OCRMyPDF(Executor):
    
    def __init__(self, command_line_options="", **kwargs) -> None:
        super().__init__()
        self.command_line_options = command_line_options
        assert isinstance(self.command_line_options, str)
    
    """
    jina executor for OCRMyPDF
    """
    @requests
    def extract_text(self, docs: DocumentArray, **kwargs):
        for doc in docs:
            # ocrmypdf.ocr(input_file=doc.uri, output_file=doc.uri, force_ocr=True, optimize=0)
            cmd = ['ocrmypdf', self.command_line_options, str(doc.uri), str(doc.uri)]
            print('command: ', ' '.join(cmd))
            p = Popen(cmd, stdout=PIPE, stderr=PIPE)
            output, err = p.communicate()
            if p.returncode != 0:
                raise Exception(f"OCRMyPDF failed with error: {err.decode('utf-8')}")
            # else:
                # print(f"OCRMyPDF succeeded with output: {output}")
            # need to reload the blob after ocrmypdf has been run
            doc.load_uri_to_blob()
[first_pdf_index.log.txt](https://github.com/jina-ai/jina/files/10404545/first_pdf_index.log.txt)

```

`configs`
```python
import os

# cur_dir = os.path.dirname(os.path.abspath(__file__))
base_dir = '/data/radiology'
model_dir = os.path.join(base_dir, 'model', '.cache')
workspace_dir = os.path.join(base_dir, 'workspace')
os.environ['JINA_PORT'] = '45678'  # the port for accessing the RESTful service, i.e. http://localhost:45678/docs
os.environ['JINA_WORKSPACE'] = workspace_dir #'./workspace'  # the directory to store the indexed data
os.environ['TOP_K'] = '50'  # the maximal number of results to return
os.environ['MODEL_MOUNT_ASSETS'] = f'{model_dir}:/tmp/.cache' #'/data/radiology/model/.cache:/tmp/.cache'
os.environ['MODEL_MOUNT_CACHE'] = f'{model_dir}:/tmp/.cache'
os.environ['WORKSPACE_MOUNT'] = f'{workspace_dir}:/workdir/workspace'
```

function to load pdf documents:
```python

def get_pdf_from_dir(dir, max=100):
    files = glob.glob(os.path.join(dir, '*.pdf'), recursive=True)
    for i,f in enumerate(files):
        doc = Document(uri=f)
        if max < 0:
            if i == 0: print('no maxiumum number of docs specified, indexing all docs...')
            yield doc
        elif i < max:
            yield doc
```

code to index:
```python
with Flow.load_config('index-pdf-flow.yml', override_with=override_dict) as f:
            for doc in get_pdf_from_dir(pdf_dir):
                print('trying to index: ', doc.uri)
                f.post(on='/index', inputs=DocumentArray([doc]), request_size=1, )

```

@JoanFM
