### ISSUE TITLE
GatewayRuntime does not respect gateway `with` parameters in config when loading a gateway

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5677]
The GatewayRuntime does not respect gateway `with` parameters in config when loading a gateway. It always overrides them with default parameters coming from the parser.
To reproduce:
`gateway --uses gateway-config.yml`
`gateway-config.yml`:
```yaml
jtype: HTTPGateway
with:
  cors: true
  protocol:
    - http
  port: 12345
```
