### ISSUE TITLE
change indexer at query time

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#587]
**Describe the feature**

Users should be able to switch between all classes inherited from `NumpyIndexer` at query time. The current serialization does seem to local the indexer to the class at index time, no way to change it (thought the log says `FaissIndexer is loaded` but actually still a `NumpyIndexer` ).

**Your proposal**

Improving the (de)serialization

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
Turns out this is nontrivial. Deserialization with this level of flexibility can not be implemented with Pickle.

On the other hand, a better solution would be allow user to wrap the existing `NumpyIndexer` with a flexible wrapper in the **query time**, e.g. 

```yaml
!WrapIndexer
with:
  idx:
    !NumpyIndexer # <--- Spec below is given by in the index time already
    metas:
      name: wrap-npidx
    with:
      backend: numpy
      compress_level: 1
      index_filename: wrap-npidx
      metric: euclidean
```

`WrapIndexer` could be advanced indexer such as `FaissIndexer`, `AnnoyIndexer`, `SPTAGIndexer`, `NmslibIndexer`. Behind the scene, it deserialization the wrapped indexer from binary file, loads the `ndarray` data, and then 

```python
self._query_handler = self.build_advanced_index(wrapped.raw_ndarray)
```

will do the trick.
