### ISSUE TITLE
gateway doesn't have secret env while enabling by adding `env-from-secret`

### ISSUE THREAD

**Issue by tarrantro** [jina-ai/jina#5913]
**Describe the bug**
I use below template to mount the secret env to flow from jina. However, gateway doesn't have such env mounted so I can't load such enviroment variable from secret.

flow 1:
```yaml
jtype: Flow
with:
  protocol: http 
  env_from_secret:
      TEST:
        name: test-secret
        key: test
executors:
  - name: sentencizer
    uses: jinahub+docker://Sentencizer
    env:
      JINA_LOG_LEVEL : DEBUG

```

flow 2:
```yaml
jtype: Flow
with:
  protocol: http
gateway:
  env_from_secret:
      TEST:
        name: test-secret
        key: test
executors:
  - name: sentencizer
    uses: jinahub+docker://Sentencizer
    env:
      JINA_LOG_LEVEL : DEBUG
```

command:
```shell
jina export kubernetes f.yaml ./my-k8s
```

gateway yaml:
```yaml
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gateway
        jina_deployment_name: gateway
        ns: default
        pod_type: GATEWAY
        shard_id: ''
    spec:
      containers:
      - args:
        - gateway
        - --k8s-namespace
        - default
        - --expose-endpoints
        - '{}'
        - --host
        - '0'
        - --uses
        - HTTPGateway
        - --graph-description
        - '{"sentencizer": ["end-gateway"], "start-gateway": ["sentencizer"]}'
        - --deployments-addresses
        - '{"sentencizer": ["grpc://sentencizer.default.svc:8080"]}'
        - --env-from-secret
        - '{"TEST": {"name": "test-secret", "key": "test"}}'
        - --port
        - '8080'
        - --protocol
        - HTTP
        - --port-monitoring
        - '9090'
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: gateway
        - name: K8S_DEPLOYMENT_NAME
          value: gateway
        - name: K8S_NAMESPACE_NAME
          value: default
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: gateway-configmap
        image: jinaai/jina:3.17.0-py38-standard
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 2
        livenessProbe:
          exec:
            command:
            - jina
            - ping
            - gateway
            - http://127.0.0.1:8080
            - --timeout 9500
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        name: gateway
        ports:
        - containerPort: 8080
        startupProbe:
          exec:
            command:
            - jina
            - ping
            - gateway
            - http://127.0.0.1:8080
          failureThreshold: 120
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
```

**Describe how you solve it**
N/A

---

**Environment**
- jina 3.17.0
- docarray 0.21.0
- jcloud 0.2.10
- jina-hubble-sdk 0.34.0
- jina-proto 0.1.27
- protobuf 3.20.3
- proto-backend cpp
- grpcio 1.47.2
- pyyaml 6.0
- python 3.9.7
- platform Linux
- platform-release 5.19.0-43-generic
- platform-version #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
- architecture x86_64
- processor x86_64
- uid 123260067508082
- session-id 168fc9c8-0e54-11ee-ad15-701ab889ef72
- uptime 2023-06-19T11:48:01.200481
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Screenshots**
N/A
