### ISSUE TITLE
Dynamic k8s namespace for generating kubernetes yaml

### ISSUE THREAD

**Issue by sansmoraxz** [jina-ai/jina#5994]
**Describe the feature**
The current implementation for to_kubernetes_yaml flow [takes `k8s_namespace` to be explicitly specified somewhere otherwise it outputs as `default` namespace](https://github.com/jina-ai/jina/blob/34664ee8db0a0e593a6c71dd6476cbf266a80641/jina/orchestrate/flow/base.py#L2772C69-L2772C69). The namespace need not be explicitly set and can be dynamically injected through metadata, hence improving the reusability of the generated templates.

For example:

```shell
kubectl apply -f "file.yaml" --namespace=prod
kubectl apply -f "file.yaml" --namespace=dev
```

**Your proposal**

We may accept that the Optional field can be `None` and propagate that when generating the yaml, in which case the generated yaml will include this for env injection:
```yaml
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

And of course we may remove the injection of namespace for all the generated objects in this case.

More info from official docs
- https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
- https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by JoanFM** [comment]
Hey @sansmoraxz,

This looks like a great feature. Since I see thwat you have digged in the code a bit, would you be up to implement it?

**Comment by sansmoraxz** [comment]
Sure

**Comment by JoanFM** [comment]
Please get in touch if you need any help, we will be welcoming your PR.

**Comment by sansmoraxz** [comment]
For deployment address (viz. injected to gateway) I see that services are being referred to by their full DNS name. Is it ok to open a sh shell, to invoke the jina cli? That way we can refer to the injected env `K8S_NAMESPACE_NAME` to refer to the executors.

Alternatively we can use with just the service name rather than the full DNS name of the service.

**Comment by JoanFM** [comment]
The namespace argument is propagated in the call to the `to_kubernetes_yaml` to every Deplpyment in the Flow, including the gateway one.

I am not sure I fully understand the question though

**Comment by sansmoraxz** [comment]
I meant assume gateway has the following gateway generation:
```yaml
containers:
      - args:
        - gateway
        - --k8s-namespace
        - default
        - --expose-endpoints
        - '{}'
        - --host
        - '1'
        - --uses
        - GRPCGateway
        - --graph-description
        - '{"executor0": ["executor1"], "start-gateway": ["executor0"], "executor1":
          ["end-gateway"]}'
        - --deployments-addresses
        - '{"executor0": ["grpc://executor0.default.svc:8080"], "executor1": ["grpc://executor1.default.svc:8080"]}'
        - --port
        - '8080'
        - --port-monitoring
        - '9090'
        command:
        - jina
```

**Comment by sansmoraxz** [comment]
We can probably try to use something like this:
```yaml
command:
        - /bin/bash
        - -c
        - jina
        - gateway
        - --k8s-namespace
        - $K8S_NAMESPACE_NAME
```

We invoke the bash first because directly passing it to the args doesn't seem to expand to the env value

**Comment by deepankarm** [comment]
> Although passing it the full service name is not really required. This works just as well

@sansmoraxz you're right. The complete FQDN is not required in deployment addresses, as both gateway & the executors are in the same namespace. We rely on service meshes (like Linkerd) that recommend using FQDNs rather than shorter names to avoid ambiguity during routing, hence we follow the best practices.

**Comment by JoanFM** [comment]
I see the problem of passing the namespace by env var to the entrypoint. Perhaps passing with ENV var syntax may work but I am not sure.

Otherwise I will take a look after holiday, thanks for your deep investigation.

**Comment by sansmoraxz** [comment]
Alternatively the jina cli can be told to look for specific environment variable names (and files) and we don't need to override the command explicitly.

**Comment by sansmoraxz** [comment]
For instance, look for the presence of `/var/run/secrets/kubernetes.io` or `.dockerenv`, to detect appropriate environments at startup. Since those are fixed name environment variable they can be directly passed. Will also make the generated manifests a lot cleaner.

**Comment by JoanFM** [comment]
I will try to look at it in more detail this incoming week and discuss some proposals about it

**Comment by JoanFM** [comment]
Hey @sansmoraxz .

I will take a look at this soon

**Comment by sansmoraxz** [comment]
My concern was that args didn't resolve for env.

Testing this small code on kubernetes 1.27:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: alpine
    command: ["echo"]
    args: ["$ENV"]
    env:
    - name: ENV
      value: "Hello World!"
  restartPolicy: OnFailure
```

The output is `$ENV`
