### ISSUE TITLE
Relese Note 3.26.0

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#6178]
# Release Note

This release contains 1 new feature and 2 fixes.

### Enable use of Python rotating logging handlers (#6167)
You can now use rotating logging handlers:
```
handlers:
  - RotatingFileHandler
level: INFO
configs:
  RotatingFileHandler:
    filename: './logs/myapp_rotating.log'
    maxBytes: 20000000  # 20MB
    backupCount: 10
    encoding: utf-8
    formatter: JsonFormatter
```
### Raise Exception if dynamic batching is activated with parameters annotation (#6176)
If an Executor in an endpoint requires `parameters`, this is incompatible with the use of `dynamic_batching` for that specific endpoint. This setting will fail.

## 🤟 Contributors

We would like to thank all contributors to this release:
- Janus Xu (@Janus-Xu)
- Joan Fontanals (@JoanFM )
