### ISSUE TITLE
Saving training data from encoder and indexing data using FAISS

### ISSUE THREAD

**Issue by howardwang15** [jina-ai/jina#637]
**Describe your problem**
I'm looking into using the `FaissIndexer` after encoding chunks. The encoder outputs a vectors of dimension D in batches but how should I be saving these vectors onto disk in a .tgz file so I can read in the training data while trying to train the indexer?

My flow currently looks like the following (adapted from the urban dict example)

```
!Flow
with:
  logserver: true
pods:
  splitter:
    yaml_path: yaml/craft_split.yml
  encoder:
    yaml_path: yaml/encode_title.yml
    timeout_ready: -1
  chunk_indexer:
    yaml_path: yaml/index_chunk.yml
  doc_indexer:
    yaml_path: yaml/index_doc.yml
    needs: gateway
  join_all:
    yaml_path: _merge
    needs: [doc_indexer, chunk_indexer]
```
and my encoder currently looks like this (doesn't actually do anything useful)

```python
class Encoder(TransformerTorchEncoder):
    def encode(self, data, *args, **kwargs):
        encoding = super().encode(data, *args, **kwargs)
        # do something with vector here...
        return encoding
``` 
One approach I'm thinking of doing is just to append the vectors into a list but I'm not sure when do write that list into a file.

**Comment by JoanFM** [comment]
Hello @howardwang15.

We are currently working on releasing a demo on how to use FaissIndexer, that you will be able to check very soon.

For the training file (.tgz) you have two options, you can generate offline with a subset of your data a .tgz file and pass it as a parameter of the FaissIndexer.
```
  - !FaissIndexer
    with:
      index_key: 'IVF10,PQ4'
      index_filename: 'faiss_index.tgz'
      train_filepath: './workspace/train.tgz'
    metas:
      workspace: './workspace'
      name: faissidx
```
Or if you want to use the complete data, you can tell FaissIndexer to use the same .tgz file that is created when the documents are indexed. 
```
  - !FaissIndexer
    with:
      index_key: 'IVF10,PQ4'
      index_filename: 'faiss_index.tgz'
      train_filepath: './workspace/faiss_index.tgz'
    metas:
      workspace: './workspace'
      name: faissidx
```

In relation with the Encoder, why do not you directly use an instance of TransformerTorchEncoder?

I hope you find these insights helpful.
