### ISSUE TITLE
Index doesn't save properly after sending IndexRequest

### ISSUE THREAD

**Issue by howardwang15** [jina-ai/jina#653]
**Describe your problem**
Thank you to the Jina team for working so hard on this project! One thing I noticed was when I send a HTTP request to `/api/index` to add new vectors to an index, even though the request is successful, the index files don't seem to be updating properly. Using the following yaml file for indexing,

```YAML
!ChunkIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vectors.gz
      metric: cosine
    metas:
      name: vecidx  # a customized name
      workspace: $WORKSPACE
  - !ChunkPbIndexer
    with:
      index_filename: chunk.gz
    metas:
      name: chunkidx  # a customized name
      workspace: $WORKSPACE
metas:
  name: chunk_indexer
  workspace: $WORKSPACE
```
I see that after sending the request, the `chunk.gz` file gets updated but not the `vectors.gz` file. Then, when I try to build a flow for searching using the index, I get the following error: `EOFError: Compressed file ended before the end-of-stream marker was reached`

**What is your guess?**
Guess is that vectors are not being saved to `vectors.gz`
---

**Environment**

**Screenshots**

![image](https://user-images.githubusercontent.com/8008938/87335455-31d07c80-c4f5-11ea-87c5-550c0c2eebb0.png)
This is the initial index build (using `ls -l` on index directory)

![image](https://user-images.githubusercontent.com/8008938/87335672-883dbb00-c4f5-11ea-8004-80ca9012ab60.png)
After sending 1 request to index 1 new vector

![image](https://user-images.githubusercontent.com/8008938/87335798-b91df000-c4f5-11ea-9011-69dc39402af1.png)
Inside of `chunk_indexer-2` directory where it appears that `vectors.gz` didn't get updated

**Comment by JoanFM** [comment]
Hello @howardwang15 .
Thank you for using Jina. I hope you like it.
Could you please provide some more information about your process and Flows (if possible) to help us in the reproduction of the issue? Like which pods compose ur flow and which type of documents are u sending or commands are you using?

**Comment by howardwang15** [comment]
Hey @JoanFM right now, I construct an index using the same script as the one in the urban-dict example. Documents are JSON objects of the form `{ "id": <>, "title":<> }`. After the index is saved, I start up a REST gateway using the flow below. The flows themselves are basically the same as the ones in the urban-dict example except I use a custom splitter and encoder. Then, I sent HTTP requests to `localhost:8080/api/index` with JSON data (of the form above). This is to simulate pretraining an index and adding new data to the index incrementally. Thanks!

```YAML
!Flow
with:
  port_expose: 8080
pods:
  splitter:
    yaml_path: pods/index/preprocess.yml
  encoder:
    yaml_path: pods/index/encode_title.yml
    timeout_ready: -1
  chunk_indexer:
    yaml_path: pods/index/index_chunk.yml
    replicas: $SHARDS
    separated_workspace: true
  doc_indexer:
    yaml_path: pods/index/index_doc.yml
    needs: gateway
  join_all:
    yaml_path: _merge
    needs: [doc_indexer, chunk_indexer]
```
