### ISSUE TITLE
🚨 BREAKING CHANGES 0.4.0 -> 0.4.1 & Migration Guide

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#702]
# Background

#652, #684, #700, #709  introduce breaking changes and new features. These features will be released in `v0.4.1`. 
Those changes are unfortunately not back-compatible. Let's write down the migration guide here.

# What has changed?

In short, the protobuf definition of `Document` and `Chunk` are unified to have the same representation. In this new representation, `Document` has a recursive structure. The previous `Chunk` is just a nested `Document` at one level deeper. The next figure illustrates this idea:

![image](https://user-images.githubusercontent.com/2041322/88682088-904f4a80-d0f2-11ea-9c99-1885a3e79d12.png)

This new proto enables cleaner driver design, yields more consistent low-level APIs, and provides great extensibility on future features, e.g. proximity graph/graph-based learning.

# Affected Versions

Since `v0.4.1`, expected on 31.07.2020.

The last version unaffected by those changes is `v0.4.0`, i.e. `pip install jina==0.4.0`

# What is affected?

Mostly drivers, some time executors. The affection is mostly due to
- As we don't distinguish chunk and doc anymore, special logic designed for `Chunk` is removed.
- As `Document` is now a recursive structure, all drivers have to work correctly by traversing the recursive structure.

# Migration Guide

- `level` is not required in all drivers anymore.

- `depth_range` controls the driver `_apply` level, the default is `depth_range=[0,0]`, i.e. working on doc level only. To mimic the previous chunk-level processing, use `depth_range=[1,1]`. `depth_range=[0,1]` means working on both doc and chunk level

- `PruneDriver` is now `ExcludeQL`, no `level` is required, `excludes` -> `fields`, e.g.
```yaml
    - !ExcludeQL
      with:
        fields:
          - embedding
          - buffer
          - blob
          - text
```

- `DocPruneDriver` is removed, one can now use 

```yaml
    - !ExcludeQL
      with:
        fields:
          - buffer
          - chunks
```

- `ChunkPruneDriver` is removed,  one can now use the following, as one can see it is basically the same as  `DocPruneDriver` , just with different fields.

```yaml
    - !ExcludeQL
      with:
        fields:
          - embedding
          - buffer
          - blob
          - text
```

- `BaseCraftDriver` is now `CraftDriver`. `DocCraftDriver` and `ChunkCraftDriver` are removed
- `doc_id` and `chunk_id` are unified as `id` now
- `UnarySegmentDriver` is removed. Now `EncodeDriver` works directly on doc-level embedding, `extract_chunks` is now refactored as `extract_docs` works on root-level extraction (previously it works on `doc.chunks` level extraction). If previously using a pod with a `UnarySegmentDriver` to connect it to an `Encoder`, you can safely remove `UnarySegmentDriver` and connect the previous pod directly to the `Encoder`.
- `BaseChunkCrafter` and `BaseDocCrafter` are removed.
- `TopkFilterDriver` is removed and now is implemented with Query Language:
```yaml
!SliceQL
with:
   start: 0
   end: k
```
- `ChunkIndexer` is now `CompoundIndexer`
- `ChunkPbIndexer` and `DocPbIndexer` are now removed, please use `BinaryPbIndexer`
- `ReqPruneDriver` is removed now use
```yaml
    - !ExcludeReqQL
      with:
        fields:
          - request
```
- `_merge_topk_docs` and `_merge_topk_chunks ` are now unified to `_merge_all`

- `yaml_path` and `image` are unified into one single keyword: `uses`. When a Pod running inside a docker container used an inner `yaml_path`, it will now use `uses_internal`.

```yaml
  !Flow
  pods:
    crafter:
      uses: yaml/craft.yml
    encoder:
      uses: jinaai/hub.executors.encoders.image.facenet
      uses_internal: yaml/encode.yml
``` 

- `reducing_yaml_path` becomes `uses_reducing`. 
```yaml
  !Flow
  pods:
    chunk_indexer:
       uses: yaml/index-chunk.yml
       separated_workspace: true
       uses_reducing: _merge_all
``` 
- `replicas` has been renamed to `parallel` with a valid alias of `shards` specially intended for `indexers` 
```yaml
  !Flow
  pods:
    encoder:
      uses: jinaai/hub.executors.encoders.image.facenet
      uses_internal: yaml/encode.yml
      parallel: 3
   chunk_indexer:
     uses: yaml/index-chunk.yml
     shards: 3
``` 
- when looping the topk results, directly access the attribute `x` without `match.x`. i.e.
```python
for k in d.matches: 
  fn(k.match.id)
```
is now 
```python
for k in d.matches: 
  fn(k.id)
```

# Related PRs

#652 #700 #684 #709
