### ISSUE TITLE
docs: hello world yaml file need to be updated

### ISSUE THREAD

**Issue by JamesTang-jinaai** [jina-ai/jina#818]
**Describe the bug**

https://docs.jina.ai/chapters/helloworld/index.html
I'm running the Hello World example. Here are the steps:

1. type the code to start up the docker image:
`docker run -v "$(pwd)/j:/j" jinaai/jina:devel hello-world --workdir /j --logserver && open j/hello-world.html`
1. make an empty folder: /software/tests, and make a file named index.yaml, here is the context:

```
!Flow
pods:
  chunk_seg:
    uses: helloworld.crafter.yml
    replicas: $REPLICAS
    read_only: true
  doc_idx:
    uses: helloworld.indexer.doc.yml
  encode:
    uses: helloworld.encoder.yml
    needs: chunk_seg
    replicas: $REPLICAS
  chunk_idx:
    uses: helloworld.indexer.chunk.yml
    replicas: $SHARDS
    separated_workspace: true
  join_all:
    uses: _merge
    needs: [doc_idx, chunk_idx]
    read_only: true
```

3. type python in the terminal, and input the python api:

```
from jina.flow import Flow

f = Flow.load_config('index.yml')

with f:
    f.index(input_fn)
```

Then I got error messages below:

`chunk_seg@23736[C]:unknown exception: ImageNotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.39/images/create?fromImage=helloworld.crafter.yml'))`

**Describe how you solve it**

1. switch the work space from /software/tests to /software/jina
2. make a new file named helloworld.flow.index.yml:

```
!Flow
with:
  logserver: $WITH_LOGSERVER
  compress_hwm: 1024
pods:
  encode:
    uses: $RESOURCE_DIR/helloworld.encoder.yml
    parallel: $PARALLEL
  index:
    uses: $RESOURCE_DIR/helloworld.indexer.yml
    shards: $SHARDS
    separated_workspace: true
```

3. rerun the python api

**Environment**

```
jina                          0.4.6
jina-proto                    0.0.58
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.1
protobuf                      3.12.4
proto-backend                 cpp
grpcio                        1.31.0
ruamel.yaml                   0.16.10
python                        3.8.2
platform                      Linux
platform-release              5.4.0-42-generic
platform-version              #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /software/jina/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)

```

**Screenshots**

![Screenshot from 2020-08-13 18-34-14](https://user-images.githubusercontent.com/69177855/90125238-42923d80-dd94-11ea-8b47-4eb4da4c0e6c.png)

![Screenshot from 2020-08-13 18-38-05](https://user-images.githubusercontent.com/69177855/90125245-4756f180-dd94-11ea-88c2-3280b5cc92bc.png)
