### ISSUE TITLE
ContainerPea not handling properly uses_internal overriding entrypoint

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#943]
**Describe the bug**
When trying to migrate `crossmodal` search example, I try to change the logic by mantaining inside `txt_emb` folder a simple config:

```yaml
!VSETextEncoder
metas:
  py_modules:
    - vocab.py
    - model.py
    - __init__.py
```

and provide from the outside with the use of `uses_internal` the file '`yaml/text_encoder.yml`:

```yaml
!VSETextEncoder
metas:
  py_modules:
    - vocab.py
    - model.py
    - __init__.py
requests:
  on:
    IndexRequest:
      - !FilterQL
        with:
          lookups: {'modality': 'text'}
      - !EncodeDriver {}
    SearchRequest:
      - !FilterQL
        with:
          lookups: {'mime_type__contains': 'text'}
      - !EncodeDriver {}
```

But it does not seem to work in the same way as having the file directly inside the docker by default. in the ENTRYPOINT.

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-230) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Ok, I think the problem will be where does it find the `py_modules`

**Comment by JoanFM** [comment]
Solution is to set the `py_modules` being aware that inside the `container` the `files would be under `workspace`:

```yaml
!VSETextEncoder
metas:
  py_modules:
    - workspace/vocab.py
    - workspace/model.py
    - workspace/__init__.py
requests:
  on:
    IndexRequest:
      - !FilterQL
        with:
          lookups: {'modality': 'text'}
      - !EncodeDriver {}
    SearchRequest:
      - !FilterQL
        with:
          lookups: {'mime_type__contains': 'text'}
      - !EncodeDriver {}
```
